config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :products
    resources :posts
    root "static_page#index"
  end

  root "static_page#edit"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  mount_uploader :name, MediaUploader
  belongs_to :product
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :posts
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: %i[admin user]

  validates :username, presence: true, length: { minimum: 6, maximum: 100 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin

    layout "admin"

    private

    def check_admin
      redirect_to root_path if current_user.role == "user"
    end
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < Admin::BaseController
    before_action :post, only: %i[destroy show update]

    def index
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(3)
    end

    def new
      @post = Post.new
      @products = Product.all
    end

    def show
      @products = Product.all
    end

    def create
      @post = Post.new post_params
      @post.save

      redirect_to admin_posts_path
    end

    def update
      @post.update post_params
      redirect_to admin_posts_path
    end

    def destroy
      @post.destroy
      redirect_to admin_posts_path
    end

    private

    def post_params
      params.require(:post).permit(:product_id, :title, :content)
    end

    def post
      @post = Post.find params[:id]
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::BaseController
    before_action :product, only: %i[show update destroy]

    def index
      @products = Product.all.order(created_at: :desc).page(params[:page]).per(5)
    end

    def show; end

    def update
      @product.update product_params
      redirect_to admin_products_path
    end

    def new
      @product = Product.new
      @product.images.build
    end

    def create
      @product = Product.new product_params

      if params[:images].present?
        @product.save
        params[:images]["image_link"].each do |a|
          @image = @product.images.create!(name: a)
        end
      end
      redirect_to admin_products_path
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path
    end

    private

    def product_params
      params.require(:product).permit :name, :price, :description,
                                      images_attributes: %i[id product_id image_link]
    end

    def product
      @product = Product.find params[:id]
    end
  end
end

app/controllers/admin/static_page_controller.rb
# frozen_string_literal: true

module Admin
  class StaticPageController < Admin::BaseController
    def index; end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_page_controller.rb
# frozen_string_literal: true

class StaticPageController < ApplicationController
  def index; end
  def show; end
  def new; end
  def edit; end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  layout "login"

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:username, :role, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "login"

  def after_sign_in_path_for(_resource)
    if current_user.role == "admin"
      admin_root_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    stored_location_for(resource) || new_user_session_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/layouts/_footer.html.slim
.container-fluid.mt--7
  footer.footer
    .row.align-items-center.justify-content-xl-between
      .col-xl-6
        .copyright.text-center.text-xl-left.text-muted
          | © 2018
          = link_to "Creative", "#", class: "font-weight-bold ml-1"
      .col-xl-6
        ul.nav.nav-footer.justify-content-center.justify-content-xl-end
          li.nav-item
            = link_to "Creative Tim", "#", class: "nav-link"
          li.nav-item
            = link_to "About Us", "#", class: "nav-link"
          li.nav-item
            = link_to "Blog", "#", class: "nav-link"
          li.nav-item
            = link_to "MIT License", "#", class: "nav-link"

app/views/admin/layouts/_header.html.slim
.main-content
  nav#navbar-main.navbar.navbar-top.navbar-expand-md.navbar-dark
    .container-fluid
      form.navbar-search.navbar-search-dark.form-inline.mr-3.d-none.d-md-flex.ml-lg-auto
        .form-group.mb-0
          .input-group.input-group-alternative
            .input-group-prepend
              span.input-group-text
                i.fas.fa-search
            input.form-control.focused placeholder="Search" type="text"
      ul.navbar-nav.align-items-center.d-none.d-md-flex
        li.nav-item.dropdown
          = link_to "#", class: "a nav-link pr-0", data: { toggle: "dropdown" }
            .media.align-items-center
              span #{current_user.username}
              | &emsp;
              span.avatar.avatar-sm.rounded-circle
                = image_tag "team-4-800x800.jpg"
          .dropdown-menu.dropdown-menu-arrow.dropdown-menu-right
            .dropdown-header.noti-title
              h6.text-overflow.m-0 Welcome!
            = link_to "#", class: "dropdown-item"
              span My profile
            = link_to "#", class: "dropdown-item"
              span Settings
            = link_to "#", class: "dropdown-item"
              span Activity
            = link_to "#", class: "dropdown-item"
              span Support
            .dropdown-divider
            = link_to destroy_user_session_path, class: "dropdown-item"
              span Logout
  .header.bg-gradient-primary.pb-8.pt-5.pt-md-8
    br
    .container-fluid
      .header-body
        .row
          .col-xl-3.col-lg-6
            .card.card-stats.mb-4.mb-xl-0
              .card-body
                .row
                  .col
                    h5.card-title.text-uppercase.text-muted.mb-0 Traffic
                    span.h2.font-weight-bold.mb-0 350,897
                  .col-auto
                    .icon.icon-shape.bg-danger.text-white.rounded-circle.shadow
                      i.fas.fa-chart-bar
                p.mt-3.mb-0.text-muted.text-sm
                  span.text-success.mr-2
                    i.fa.fa-arrow-up
                    | 3.48%
                  span.text-nowrap Since last month
          .col-xl-3.col-lg-6
            .card.card-stats.mb-4.mb-xl-0
              .card-body
                .row
                  .col
                    h5.card-title.text-uppercase.text-muted.mb-0 New users
                    span.h2.font-weight-bold.mb-0 2,356
                  .col-auto
                    .icon.icon-shape.bg-warning.text-white.rounded-circle.shadow
                      i.fas.fa-chart-pie
                p.mt-3.mb-0.text-muted.text-sm
                  span.text-danger.mr-2
                    i.fas.fa-arrow-down
                    | 3.48%
                  span.text-nowrap Since last week
          .col-xl-3.col-lg-6
            .card.card-stats.mb-4.mb-xl-0
              .card-body
                .row
                  .col
                    h5.card-title.text-uppercase.text-muted.mb-0 Sales
                    span.h2.font-weight-bold.mb-0 924
                  .col-auto
                    .icon.icon-shape.bg-yellow.text-white.rounded-circle.shadow
                      i.fas.fa-users
                p.mt-3.mb-0.text-muted.text-sm
                  span.text-warning.mr-2
                    i.fas.fa-arrow-down
                    | 1.10%
                  span.text-nowrap Since yesterday
          .col-xl-3.col-lg-6
            .card.card-stats.mb-4.mb-xl-0
              .card-body
                .row
                  .col
                    h5.card-title.text-uppercase.text-muted.mb-0 Performance
                    span.h2.font-weight-bold.mb-0 49,65%
                  .col-auto
                    .icon.icon-shape.bg-info.text-white.rounded-circle.shadow
                      i.fas.fa-percent
                p.mt-3.mb-0.text-muted.text-sm
                  span.text-success.mr-2
                    i.fas.fa-arrow-up
                    | 12%
                  span.text-nowrap Since last month

app/views/admin/layouts/_sidebar.html.slim
nav#sidenav-main.navbar.navbar-vertical.fixed-left.navbar-expand-md.navbar-light.bg-white
  .container-fluid
    = link_to admin_root_path, class: "navbar-brand pt-0"
      = image_tag "blue.png"
    #sidenav-collapse-main.collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item
          = link_to "#", class: "nav-link active"
            i.fas.fa-tachometer-alt
            | Dashboard
        li.nav-item
          = link_to admin_products_path, class: "nav-link"
            i.fas.fa-tree
            | Products
        li.nav-item
          = link_to admin_posts_path, class: "nav-link"
            i.fas.fa-tree
            | Blogs
        li.nav-item
          = link_to "#", class: "nav-link"
            i.fas.fa-map-marked-alt
            | Maps
        li.nav-item
          = link_to "#", class: "nav-link"
            i.fas.fa-user
            | User profile
        li.nav-item
          = link_to "#", class: "nav-link"
            i.fas.fa-table
            | Tables
        li.nav-item
          = link_to destroy_user_session_path, class: "nav-link" 
            i.fas.fa-sign-in-alt
            | Logout

app/views/admin/posts/_row.html.slim
tr
  th scope="row"
    span.mb-0.text-sm &emsp; #{ post.title }
  td
    | #{ raw post.content.truncate(30) }
  td
    | #{ post.product.name }
  td.text-right
    .dropdown
      a.btn.btn-sm.btn-icon-only.text-light data-toggle="dropdown" href="#" role="button" 
        i.fas.fa-chevron-circle-down
      .dropdown-menu.dropdown-menu-right.dropdown-menu-arrow
        = link_to "Show", admin_post_path(post), class: "dropdown-item"
        = link_to "Delete", admin_post_path(post), method: :delete, class: "dropdown-item"

app/views/admin/posts/index.html.slim
.main-content.table-with
  .container-fluid.mt--7
    .row
      .col
        .card.shadow
          .card-header.border-0
            h3.mb-0 Card tables
            = link_to "New post", new_admin_post_path, {style: "float: right;"}
          .table-responsive
            table.table.align-items-center.table-flush
              thead.thead-light
                tr
                  th scope="col"  Title
                  th scope="col"  Content
                  th scope="col"  Product
                  th scope="col"  Action 
              tbody
                = render partial: "row", collection: @posts, as: :post
          .card-footer.py-4
            = paginate @posts, theme: "twitter-bootstrap-4"

app/views/admin/posts/new.html.slim
.main-content
  .container-fluid.mt--7
    .col-xl-8.order-xl-1.form-add-product
      .card.bg-secondary.shadow
        .card-header.bg-white.border-0
          .row.align-items-center
            .col-8
              h3.mb-0 New Blog
        .card-body
          = form_for @post, url: admin_posts_path do |f|
            .text-right
              = f.select :product_id, options_for_select(@products.collect{ |u| [u.name, u.id] })
              | &emsp;
              = f.submit "Create blog", class: "btn btn-sm btn-primary"
            h6.heading-small.text-muted.mb-4 Blog information
            .pl-lg-4
              .row
                .col-lg-12
                  .form-group.focused
                    = f.label :title, class: "form-control-label"
                    = f.text_field :title, required: true, class: "form-control form-control-alternative"
            hr.my-4
            h6.heading-small.text-muted.mb-4 Description
            .pl-lg-4
              .form-group.focused
                = f.text_area :content, required: true, class: "ckeditor" , placeholder: "A few words about you ..."
            hr.my-4

app/views/admin/posts/show.html.slim
.main-content
  .container-fluid.mt--7
    .col-xl-8.order-xl-1.form-add-product
      .card.bg-secondary.shadow
        .card-header.bg-white.border-0
          .row.align-items-center
            .col-8
              h3.mb-0 Show Blog
        .card-body
          = form_for @post, url: admin_post_path do |f|
            .text-right
              = f.select :product_id, options_for_select(@products.collect{ |u| [u.name, u.id] })
              | &emsp;
              = f.submit "Save blog", class: "btn btn-sm btn-primary"
            h6.heading-small.text-muted.mb-4 Blog information
            .pl-lg-4
              .row
                .col-lg-12
                  .form-group.focused
                    = f.label :title, class: "form-control-label"
                    = f.text_field :title, required: true, class: "form-control form-control-alternative"
            hr.my-4
            h6.heading-small.text-muted.mb-4 Description
            .pl-lg-4
              .form-group.focused
                = f.text_area :content, required: true, class: "ckeditor" , placeholder: "A few words about you ..."
            hr.my-4

app/views/admin/products/_row.html.slim
tr
  th scope="row" 
    .media.align-items-center
      = link_to "#", class: "avatar rounded-circle"
        = image_tag product.images.first.name_url if product.images.present?
      .media-body
        span.mb-0.text-sm &emsp; #{ product.name }
  td
    | #{ number_to_currency( product.price ) }
  td
    .avatar-group
      = link_to "#", class: "avatar avatar-sm", :data => { toggle: "tooltip" }, "data-original-title" => "Ryan Tompson"
        = image_tag "team-4-800x800.jpg", class: "rounded-circle"
  td
    .d-flex.align-items-center
      span.mr-2 80%
      div
        .progress
          .progress-bar.bg-warning aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" style=("width: 60%;") 
  td.text-right
    .dropdown
      a.btn.btn-sm.btn-icon-only.text-light data-toggle="dropdown" href="#" role="button" 
        i.fas.fa-chevron-circle-down
      .dropdown-menu.dropdown-menu-right.dropdown-menu-arrow
        = link_to "Show", admin_product_path(product), class: "dropdown-item"
        = link_to "Delete", admin_product_path(product), method: :delete, class: "dropdown-item"

app/views/admin/products/index.html.slim
.main-content.table-with
  .container-fluid.mt--7
    .row
      .col
        .card.shadow
          .card-header.border-0
            h3.mb-0 Card tables
            = link_to "New product", new_admin_product_path, {style: "float: right;"}
          .table-responsive
            table.table.align-items-center.table-flush
              thead.thead-light
                tr
                  th scope="col"  Product
                  th scope="col"  Price
                  th scope="col"  Users
                  th scope="col"  Completion
                  th scope="col"  Action 
              tbody
                = render partial: "row", collection: @products, as: :product
          .card-footer.py-4
            = paginate @products, theme: "twitter-bootstrap-4"
                  

app/views/admin/products/new.html.slim
.main-content
  .container-fluid.mt--7
    .col-xl-8.order-xl-1.form-add-product
      .card.bg-secondary.shadow
        .card-header.bg-white.border-0
          .row.align-items-center
            .col-8
              h3.mb-0 Add product
        .card-body
          = form_for @product, url: admin_products_path do |f|
            .text-right
              = f.submit "Add product", class: "btn btn-sm btn-primary"
            h6.heading-small.text-muted.mb-4 Product information
            .pl-lg-4
              .row
                .col-lg-6
                  .form-group.focused
                    = f.label :name, class: "form-control-label"
                    = f.text_field :name, required: true, class: "form-control form-control-alternative"
                .col-lg-6
                  .form-group
                    = f.label :price, class: "form-control-label"
                    = f.text_field :price, required: true, class: "form-control form-control-alternative", type: "number"
            hr.my-4
            h6.heading-small.text-muted.mb-4 Description
            .pl-lg-4
              .form-group.focused
                = f.text_area :description, required: true, class:"form-control form-control-alternative", placeholder: "A few words about you ..."
            hr.my-4
            h6.heading-small.text-muted.mb-4 Add image
            .pl-lg-4
              .fallback
                = f.fields_for :images do |p|
                  = p.file_field :image, multiple: true, name: "images[image_link][]", class: "upload-image", id: "input_files"

app/views/admin/products/show.html.slim
.main-content
  .container-fluid.mt--7
    .col-xl-8.order-xl-1.form-add-product
      .card.bg-secondary.shadow
        .card-header.bg-white.border-0
          .row.align-items-center
            .col-8
              h3.mb-0 Update product
        .card-body
          = form_for @product, url: admin_product_path do |f|
            .text-right
              = f.submit "Update", class: "btn btn-sm btn-primary"
            h6.heading-small.text-muted.mb-4 Product information
            .pl-lg-4
              .row
                .col-lg-6
                  .form-group.focused
                    = f.label :name, class: "form-control-label"
                    = f.text_field :name, required: true, class: "form-control form-control-alternative"
                .col-lg-6
                  .form-group
                    = f.label :price, class: "form-control-label"
                    = f.text_field :price, required: true, class: "form-control form-control-alternative", type: "number"
            hr.my-4
            h6.heading-small.text-muted.mb-4 Description
            .pl-lg-4
              .form-group.focused
                = f.text_area :description, required: true, class:"form-control form-control-alternative", placeholder: "A few words about you ..."
            hr.my-4

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Admin
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = render "admin/layouts/sidebar"
  body
  	= render "admin/layouts/header"
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeachBlossom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8748c74444.js"></script>
    <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Admin
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
  .bg-default
    .main-content
      = render "users/shared/header"
      = yield
      = render "users/shared/footer"

app/views/static_page/edit.html.slim
header.phantren
  .menu
  .hieuung
    .anhnen
    = image_tag "cogai.png", class: "cogai"
    .chuto 
      span.chuso 1000 
      | opportunities
    .chunho
      | The easiest way to build different sites
    .nut 
      | Make an appoinment

app/views/static_page/index.html.slim
header
  nav.menutren
    ul
      li 
        = link_to "CHAPTER 1", "#"
      li
        = link_to "CHAPTER 2", "#"
      li
        = link_to "CHAPTER 3", "#"
      li
        = link_to "CHAPTER 4", "#"
.home
.noidung1
  h2.cangiua Được đào tạo các kỹ năng, tư duy lập trình chuyên sâu trên các sản phẩm, dự án thực tế
.chapter1
  h2.chuto 1
.noidung2
  h2.cangiua Được đào tạo các kỹ năng, tư duy lập trình chuyên sâu trên các sản phẩm, dự án thực tế
.chapter2
  h2.chuto 2
.noidung3
  h2.cangiua Được đào tạo các kỹ năng, tư duy lập trình chuyên sâu trên các sản phẩm, dự án thực tế
.chapter3
  h2.chuto 3
.noidung4
  h2.cangiua Được đào tạo các kỹ năng, tư duy lập trình chuyên sâu trên các sản phẩm, dự án thực tế
.chapter4
  h2.chuto 4
.nutlentren Back To Top

app/views/static_page/new.html.slim
.ratto
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making..tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making..tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "9.jpg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "10.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "8.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "9.jpg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .tinto
    = image_tag "10.jpeg", class: "layer1"
    .xam
    .gradient
    .hinhvuong
    .chuto
      | Warm Oscar
    .chunho
      | Although Rails is designed for making.
  .noidungthem
    .tinto
      = image_tag "8.jpeg", class: "layer1"
      .xam
      .gradient
      .hinhvuong
      .chuto
        | Warm Oscar
      .chunho
        | Although Rails is designed for making.
    .tinto
      = image_tag "8.jpeg", class: "layer1"
      .xam
      .gradient
      .hinhvuong
      .chuto
        | Warm Oscar
      .chunho
        | Although Rails is designed for making.
    .tinto
      = image_tag "8.jpeg", class: "layer1"
      .xam
      .gradient
      .hinhvuong
      .chuto
        | Warm Oscar
      .chunho
        | Although Rails is designed for making.
    .tinto
      = image_tag "9.jpg", class: "layer1"
      .xam
      .gradient
      .hinhvuong
      .chuto
        | Warm Oscar
      .chunho
        | Although Rails is designed for making.
    .tinto
      = image_tag "10.jpeg", class: "layer1"
      .xam
      .gradient
      .hinhvuong
      .chuto
        | Warm Oscar
      .chunho
        | Although Rails is designed for making.
  .loadthem
    button.nutload Load them noi dung

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_footer.html.slim
footer.py-5
  .container
    .row.align-items-center.justify-content-xl-between
      .col-xl-6
        .copyright.text-center.text-xl-left.text-muted
          | © 2018
          = link_to "Creative Tim", "#", class: "font-weight-bold ml-1"
      .col-xl-6
        ul.nav.nav-footer.justify-content-center.justify-content-xl-end
          li.nav-item
            = link_to "Creative Tim", "#", class: "nav-link"
          li.nav-item
            = link_to "About Us", "#", class: "nav-link"
          li.nav-item
            = link_to "Blog", "#", class: "nav-link"
          li.nav-item
            = link_to "MIT License", "#", class: "nav-link"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_user_session_path %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_user_registration_path %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_user_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_user_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>